feane_settup/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',include('customer.urls'),name='customer'),
    path('admin/',include('feaneAdmin.urls'),name='admin'),
    path('store/',include('store.urls'),name='store'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.store,name='store'),
    path('search',views.search,name='search'),
    path('<int:id>',views.store,name='store'),
    path('product/<id>',views.product,name='product'),
    path('cart',views.cart, name='cart'),
    path('addToCart',views.addToCart, name ="addToCart"),
    path('removefromcart/<id>',views.removefromcart, name ="removefromcart"),
    path('checkout',views.checkout,name='checkout'),
    path('placeOrder',views.placeOrder,name='placeOrder'),
    path('cartItems',views.cartItems,name='cartItems'),
    path('cart_count_change',views.cart_count_change,name='cart_count_change'),

    path('cart_in_order/<id>',views.user_order,name='cart_in_order'),
    path('user_order',views.user_order,name='user_order'),

    path('user_order_history',views.user_order_history,name='user_order_history'),
    path('user_order_history_cart/<id>',views.user_order_history,name='user_order_history_cart'),
    
    path('payment_callback/<id>', views.payment_callback, name='payment_callback'),
    path('wallet', views.wallet, name='wallet'),
    path('cancel_request/<order_id>', views.cancel_request, name='cancel_request'),

    path('check_coupon', views.check_coupon, name='check_coupon'),  

    path('invoice/<order_id>', views.invoice, name='invoice'),  
]

customer/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,BaseUserManager
from django.utils.translation import gettext_lazy as _
from store.models import Cart
from feaneAdmin.models import Notification

# Custom USER models here. email and password for authentication
###########################################
class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    phone_number = models.CharField(max_length=13)
    phone_number_verified = models.BooleanField(_(""),default=False)
    otp = models.IntegerField(default=0000,null=True)
    email = models.EmailField(_('email address'),unique=True)
    blocked = models.BooleanField(_(""),default=False)
    updated_at = models.DateField(_(""), auto_now=True, auto_now_add=False)
    is_deleted = models.BooleanField(_(""),default=False)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()
    
    @property
    def wallet_balance(self):
        wallet = Wallet.objects.filter(user = self)
        if wallet is not None:
            balance = sum([item.amount for item in wallet])
            return balance
        else:
            return 0
    
    @property
    def cart_count(self):
        cart_count = Cart.objects.filter(user = self,purchased = False).count()
        return cart_count

    @property
    def messages(self):
        mess = Message.objects.filter(user = self,is_deleted = False,is_read = False)
        return mess
    
    @property
    def notification(self):
        notifications = Notification.objects.filter(is_read = False, is_deleted = False)
        for item in notifications:
            print(item.heading)
        return notifications



class Address(models.Model):
    user = models.ForeignKey("User", verbose_name=_(""), on_delete=models.CASCADE)
    house_number = models.CharField(_(""), max_length=50)
    building_number = models.CharField(_(""), max_length=50)
    street_name = models.CharField(_(""), max_length=50)
    city = models.CharField(_(""), max_length=50)
    pin_number = models.IntegerField(_(""))
    phone_number = models.CharField(_(""), max_length=50)
    disabled = models.BooleanField(_(""),default=False)
    last_modified = models.DateField(_(""), auto_now=True, auto_now_add=False)
    is_deleted = models.BooleanField(_(""),default=False)

class Wallet(models.Model):
    TRANSACTION_CHOICES = (
        ('1', 'Cancellation'),
        ('2', 'Deposit'),
        ('3', 'Payment'),
        ('4', 'Others'),
        ('5', 'Order refusal')
    )
    user = models.ForeignKey("User", verbose_name=_(""), on_delete=models.CASCADE)
    transaction_date = models.DateTimeField(_(""), auto_now=False, auto_now_add=True)
    transaction_type = models.CharField(max_length=20, choices=TRANSACTION_CHOICES,default='1')
    order = models.ForeignKey("store.Order", verbose_name=_(""), on_delete=models.CASCADE,null=True)
    amount = models.FloatField(_(""),default= 0)

class Message(models.Model):
    def get_default_user():
        return 
    user = models.ForeignKey("User", verbose_name=_(""), on_delete=models.CASCADE,related_name="recieved")
    heading = models.TextField(_(""))
    text = models.TextField(_(""))
    sender = models.ForeignKey("User", verbose_name=_(""), on_delete=models.CASCADE,default=get_default_user)
    created_at = models.DateTimeField(_(""), auto_now=False, auto_now_add=True)
    modified_at = models.DateTimeField(_(""), auto_now=True, auto_now_add=False)
    is_read = models.BooleanField(_(""),default=False)
    is_deleted = models.BooleanField(_(""),default= False)

templates/adminbase.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
   <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">

  {% block styles %}
    
  {% endblock %}

  <title> Feane </title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.3.1/jspdf.umd.min.js"></script>

</head>

<body class="sub_page">
    <div class="hero_area position-fixed w-100 z-3">
        <div class="bg-box bg-black">
            
        </div>
        <!-- header section strats -->
        <header class="header_section">
            <div class="container">
                <nav class="navbar navbar-expand-lg custom_nav-container ">
                    <a class="navbar-brand" href=" {% url 'admin_home' %} ">
                        <span>
                            Feane Admin
                        </span>
                    </a>

                    <!-- <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class=""> </span>
                    </button> -->

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav  mx-auto ">
                            <li class="nav-item ">
                                <a class="nav-link" href=" {% url 'admin_home' %}">Home </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'show_orders' %}">Orders</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users' %}">Users <span class="sr-only">(current)</span> </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'inventory' %} ">Inventory</a>
                            </li>
                        </ul>
                        <div class="user_option">
                            
                            <div class=" px-5 " >
                                <span class="text-white-50 h6 ">
                                    {{request.user.email}}
                                </span>
                                <a href=" {% url 'admin_signout' %} " class="order_online">
                                    Logout
                                </a>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </header>
        <!-- end header section -->
    </div>
    <!-- body section -->
    <div class="container-fluid bg-black min-vh-100  food_section layout_padding ">
    {% block page-content  %}

    {% endblock  %}
    </div>
    {% block scripts %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
      <!-- body section end -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
      <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
      <!-- popper js -->
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
      </script>
      <!-- bootstrap js -->
      
      <!-- owl slider -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
      </script>
      <!-- isotope js -->
      <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
      <!-- nice select -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
      <!-- custom js -->

</body>

</html>

templates/index.html
{% extends 'base.html' %}
  <!-- food section -->
{% block page-content %}
{% load static %}
  <section class="food_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Our Menu
        </h2>
      </div>
      <form action="{% url 'search' %}" method="post">
        {% csrf_token %}
        <div class="input-group d-flex justify-content-end">
          <div class="form-outline">
            <input name="search-term" type="search" id="form1" class="form-control" placeholder="search" value = "{{search_term}}" />
          </div>
          <button type="submit" class="btn btn-warning">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </form>
      
      <ul class="filters_menu">
        <a href="{% url 'store' %}?search_term={{search_term}}"><li data-filter="*" class="text-dark"   id = "all" >All</li></a>
        {% for item in category %}
        <a href="{% url 'store' item.id%}?search_term={{search_term}}"><li class="text-dark" id="{{item.id}}">{{ item.category_name }}</li></a>
        {% endfor %}
        <!-- <li data-filter=".pizza">Pizza</li>
        <li data-filter=".pasta">Pasta</li>
        <li data-filter=".fries">Fries</li> -->
      </ul>
        
      <div class="filters-content">
        <div class="row grid">
          
          {% for product in products %}
          <div class="col-sm-6 col-lg-4 all {{product.product_category.category_name}}">           
            <div class="box">
              <div>
                <a href="./product/{{product.id}}">
                  <div class="img-box">
                    {% if product.first_image %}
                      <img src="{{ product.first_image.url}}">
                    {% endif %}
                  </div>
                </a>
                <div class="detail-box">
                  <h5>
                    {{ product.product_name }}
                  </h5>
                  <p class="text-truncate">
                    {{ product.product_text }}
                  </p>
                  <p>
                    {{ product.product_size.size_type }}
                  </p>
                  <div class="options">
                    <h6>
                     Rs {{ product.product_prize }}
                    </h6>
                    <span type="text" id="{{ product.id }}" hidden>{{ product.id }} </span>
                    <form action="">{% csrf_token %}</form>
                    <button class="rounded-circle bg-warning" onclick="addToCart({{ product.id}})" name="tooltip-btn" id = "tooltip{{product.id}}" data-toggle="tooltip" data-placement="bottom" >
                      <img class="" src="{% static 'images/cart-icon.svg' %}" alt="">
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          {% comment %} Box {% endcomment %}
          
        </div>
      </div>
      <div class="btn-box">
        {% if products.has_previous %}
            <a href="?page={{ products.previous_page_number }}&item={{item}}&search_term={{search_term}}">prev</a>
        {% endif %}
        {% if products.has_next %}
            <a href="?page={{ products.next_page_number }}&item={{item}}&search_term={{search_term}}">next</a>
        {% endif %}
      </div>
    </div>
</section>
<input type="text" id="cat_id" name="" value="{{item}}" hidden>
<script>
function addToCart(p){
    const product_id = p
    let quantity = 0
    let csrf_token = document.getElementsByName("csrfmiddlewaretoken")[0].value;
    let btn = document.getElementById("tooltip"+p)

    data = JSON.stringify({'product_id': product_id, 'quantity': quantity})
    var xhr = new XMLHttpRequest();
    xhr.open("POST", "/store/addToCart", true);
    xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
    xhr.setRequestHeader("X-CSRFToken", csrf_token);
    xhr.onreadystatechange = function() {      
        if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
            console.log(xhr.responseText);
            var response = JSON.parse(xhr.responseText); 
            document.getElementById('cart_count').innerHTML = response.cart_count
            btn.setAttribute("title", "Already added to cart");     
        };
    }
    xhr.send(data);
}

window.onload = function(){
  
  var xhr = new XMLHttpRequest();
  xhr.open("GET", "/store/cartItems", true);
    xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
    // xhr.setRequestHeader("X-CSRFToken", csrf_token);
    xhr.onreadystatechange = function() {      
        if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
            var response = JSON.parse(xhr.responseText); 
            const myList = response.myList;
            myList.forEach(function(item) {
              tooltip_btns = document.getElementById("tooltip"+item)
              tooltip_btns.setAttribute("title", "Already added to cart");
            });
            
        };
    }
    xhr.send();
    

  let id = document.getElementById('cat_id').value
  if (id != "None")
    document.getElementById(id).classList.add('bg-warning');
  else
    document.getElementById('all').classList.add('bg-warning');
  console.log(id);
  }
  
</script>
{% block scripts %}
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/helper.js' %}"></script>
<script src=" {% static 'js/confirmation.js' %} "></script>
{% endblock scripts %}
  

  {% endblock page-content %}
  
  <!-- end food section -->

  

templates/message_all.html
{% extends 'adminbase.html' %}

{% block page-content %}
<div class="container">
	<nav class="navbar navbar-expand-lg navbar-light bg-black">
		<div class="container-fluid">
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse py-2 border border-white rounded-3" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item px-3">
						<a class="nav-link active text-white rounded-3" id="users" aria-current="page" href="{% url 'users' %}">All users</a>
					</li>
					<li class="nav-item px-3">
						<a class="nav-link text-white rounded-3" id="blocked_users" href="{% url 'blocked_users' %}">Blocked Users</a>
					</li>
					<li class="nav-item px-3">
						<a class="nav-link text-white rounded-3 bg-dark" id="message_all_users" href="{% url 'message_all_users' %}">Message to users</a>
					</li>
					
				</ul>
				<!-- <form class="d-flex px-3" method="post" action="{% url 'adminside_search' %}">
					{% csrf_token %}
					<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name = "search_string">
					<input type="text" name="item" value="user" hidden>
					<input type="text" name="blocked" value="{{blocked}}" hidden>
					<button class="btn btn-outline-success" type="submit">Search</button>
				</form> -->
			</div>
		</div>
	</nav>
</div>
<div class="container text-white">
    <div class="row justify-content-center align-items-center g-2">
        <div class="col-md-3"></div>
        <div class="col">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Heading</label>
                    <input type="text" class="form-control" id="exampleFormControlInput1" name="heading" placeholder="Header for the message" required>
                  </div>
                  <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Text</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" name="text" rows="3" required></textarea>
                  </div>
                  <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Photo *Optional</label>
                    <input type="file" class="form-control" name="image" id="exampleFormControlInput1">
                  </div>
                  <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label"></label>
                    <button class="btn btn-primary" type="submit">Push</button>
                  </div>
            </form>
                
        </div>
        <div class="col-md-3"></div>
    </div>
</div>




{% endblock page-content %}

templates/messages.html
{% extends 'base.html' %}
{% block page-content %}
    
    <div class="container">
        <div class="row justify-content-center align-items-start g-2">
            <!-- <div class="col-md-3"></div> -->
            <div class="col-md-6">
                {% if notifications %}
                <h4 class="text-center">Notifications</h4>
                {% endif %}
                {% for message in notifications %}
                    <div class="card m-4">
                        <div class="card-header">
                            {{message.heading}}
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{message.text}}</p>
                        </div>
                        {% if message.image %}
                        <div class="card-body text-center">
                            <img class="img-fluid w-50" src="{{message.image.url}}" alt="">    
                        </div>
                        {% endif %}
                        <div class="card-body">
                            <p class="card-text">{{message.created_at}}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-md-6">
                {% if messages %}
                <h4 class="text-center">Your Messages</h4>
                {% endif %}
                {% for message in messages %}
                    <div class="card m-4">
                        <div class="card-header">
                            {{message.heading}}
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{message.text}}</p>
                        </div>
                        {% if message.image.url %}
                        <div class="card-body text-center">
                            <img class="img-fluid w-50" src="{{message.image.url}}" alt=""> 
                        </div>
                        {% endif %}
                        <div class="card-body">
                            <p class="card-text">{{message.created_at}}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
            
        </div>
    </div>

{% endblock %}

templates/payment.html
{% extends 'base.html' %}

{% block page-content %}
<input hidden type="text" id="YOUR_KEY_ID" value="{{YOUR_KEY_ID}}">
<input hidden type="text" id="order_id" value="{{order_id}}">
<input hidden type="text" id="name" value="{{name}}">
<input hidden type="text" id="email" value="{{email}}">
<input hidden type="text" id="contact" value="{{contact}}">
<button hidden id="rzp-button1" >Pay</button>


<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
    YOUR_KEY_ID = document.getElementById('YOUR_KEY_ID').value
    order_id = document.getElementById('order_id').value
    name = document.getElementById('name').value
    email = document.getElementById('email').value
    contact = document.getElementById('contact').value
    btn = document.getElementById('rzp-button1')
var options = {
    "key": YOUR_KEY_ID, // Enter the Key ID generated from the Dashboard
    "amount": {{amount}}, // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "name": "Feane",
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": order_id, //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "handler": function (response){    
        window.location.href = '/store/payment_callback/'+response.razorpay_payment_id.toString()
    },
    "prefill": {
        "name": name,
        "email": email,
        "contact": contact
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    },
    
};

var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
    id = response.error.metadata.payment_id
    url = '/store/payment_callback/'+id.toString()
    console.log(url);
    window.location.href = url
        
});

window.onload = function(e){
    rzp1.open();
    e.preventDefault();
}

</script>

{% endblock %}

templates/user_update.html
{% extends 'adminbase.html' %}
{% load static %}

{% block scripts %}
    <script src="{% static 'js/confirmation.js' %}"></script>
{% endblock %}



{% block page-content %}
<style>
    #blk-box{
        display: none;
        
    }
    #dlt-box{
        display: none;
    }
      
</style>
    <div class="container ">
        <div class="row justify-content-center align-items-center pt-5">
            <div class="col-md-6 ">
                <form action="{% url 'user_update' user.id %}" method="post">
                    {% csrf_token %}
                    <div>
                        <label for="bane" class=" pt-2 text-white ">First Name </label>
                        <input type="text" class="form-control " placeholder="Users Name" name="name" value="{{user.first_name}}" readonly />
                    </div>
                    <div>
                        <label for="bane" class=" pt-2 text-white">Mobile </label>
                        <input type="text" class="form-control" placeholder="Users Phone Number" name="number" value="{{user.phone_number}}" readonly/>
                    </div>
                    <div>
                        <label for="bane" class=" pt-2 text-white">Email </label>
                        <input type="email" class="form-control" placeholder="Users Your Email" name="email" value="{{user.email}}" readonly />
                    </div>
                    <div class="btn_box p-3 ">
        
                    </div>
                </form>
            </div>
            <div class="col-md-6 d-flex flex-column justify-content-center align-items-center">
                <!-- <a class=" p-2 " id="dltbtn"  >               
                    <button class=" btn-danger " type="submit">DELETE USER</button>
                </a>
                <div id="dlt-box" class="w-50 bg-black position-absolute">
                    <p class=" text-center text-danger">Are you sure ? <br> <span class="text-bg-warning text-black font-weight-bold"> DELETE !!</span></p>
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-success mx-2" id="nodel">NO</button>
                        <a class="btn btn-danger mx-2" href="{% url 'delete_profile' user.id %}" >YES</a>
                        
                    </div>   
                </div> -->



                {% if user.blocked %}
                <p class="m-0" >This user is blocked</p>
                <a class=" p-2 " href="{% url 'unblock_user' user.id %}" >           
                    <button class=" btn-danger " type="button">UN BLOCK</button>
                </a>
                
                {% else %}
                <a class="p-2" id="blockbtn" >               
                    <button class="btn-danger " type="button">BLOCK USER</button>
                </a>
                <div id="blk-box" class="w-50 bg-black position-absolute">
                    <p class=" text-center text-danger">Are you sure  ?<br><span class=" font-weight-bold"> BLOCK !!</span></p>
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-success mx-2" id="no">NO</button>
                        <a class="btn btn-danger mx-2" href="{% url 'block_user' user.id %}" id="yes">YES</a>  
                    </div>   
                </div>

                {% endif %}
                
                
            </div>
        </div>
    </div>

<script>
   
</script>

{% endblock page-content %}

templates/wallet.html
{% extends 'base.html' %}

{% block page-content %}
    
    <div class="container">
        <div class="d-flex justify-content-end">
            <h5>Balance : Rs {{request.user.wallet_balance}}</h5>
        </div>
        <div class="d-flex justify-content-center">
            <table class="table w-75">
                <thead>
                  <tr class="text-center">
                    <th scope="col">#</th>
                    <th scope="col">Date</th>
                    <th scope="col">Transaction type</th>
                    <th scope="col">Amount</th>
                  </tr>
                </thead>
                <tbody class="text-center">
                {% for item in wallet  %}
                  <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{item.transaction_date}}</td>
                    <td>{{item.get_transaction_type_display}}</td>
                    <td>{{item.amount}}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
    <div class="pagination d-flex justify-content-center">
      <span class="step-links">
          {% if wallet.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ wallet.previous_page_number }}">&lsaquo; previous</a>
          {% endif %}
  
          <span class="current-page">
              Page {{ wallet.number }} of {{ wallet.paginator.num_pages }}.
          </span>
  
          {% if wallet.has_next %}
              <a href="?page={{ wallet.next_page_number }}">next &rsaquo;</a>
              <a href="?page={{ wallet.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
      </span>
  </div>
{% endblock %}